### ISSUE TITLE
DB migrations -  schema version/updater feature.

### ISSUE THREAD

**Issue by ceckoslab** [basicrum/front_basicrum_go#60]
Today we are keeping the **webperf_rum_events** table definition in **dao/dao.go** and the table gets created on startup if the table doesn't exist.

If we want to add a new field or to modify an existing one we have 2 possibilities:

1. Drop the table, change the create SQL in **dao/dao.go** and restart the **Front Basic RUM GO** server.
2. Connect directly to the ClickHouse DB and manually run an ALTER TABLE statement.

The 2 approaches are suitable during development but don't seem to be a good idea when **Front Basic RUM GO** will be used on production.

That's why we will need a solution for database migrations like: https://github.com/golang-migrate/migrate 

Some things to consider:

Check if we can use table prefixes in the migration scripts because **Front Basic RUM GO** allows us to define a table prefix in the startup config by defining a prefix in the **DATABASE_TABLE_PREFIX** environment variable.

**Comment by ivan-stankov-golang** [comment]
https://clickhouse.uptrace.dev/guide/migrations.html#migration-names
