### ISSUE TITLE
Verify that the Let's encrypt setup works.

### ISSUE THREAD

**Issue by ceckoslab** [basicrum/front_basicrum_go#89]
I was playing with provisioning the component with the Let's Encrypt option.

I used CloudFlare for DNS and Hetzner for hosting:
 * After I started a new cloud server I got the public IP of the server.
 * I added the IP and the subdomain in Cloudflare which helped with DNS resolve.

Here are the SSL related environment variables:
```
BRUM_SERVER_SSL=true
BRUM_SERVER_SSL_TYPE=LETS_ENCRYPT
BRUM_SERVER_SSL_LETS_ENCRYPT_DOMAIN=testsubdomain.basicrum.com
```

For some reason I couldn't make it work. 

For reference I tried with self-signed certificate and which worked just fine.

Ivan could you take a look and check if this is a real problem?

**Comment by ivan-stankov-golang** [comment]
How to connect to this server ?

**Comment by ivan-stankov-golang** [comment]
https://github.com/basicrum/basicrum-all-in-one/pull/170

**Comment by ceckoslab** [comment]
It works after merging #91
